# fly.toml app configuration file generated for base-project on 2026-02-20T14:54:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'base-project'
primary_region = 'nrt'
console_command = 'python manage.py shell'

[build]

[env]
  DEBUG = 'False'
  ALLOWED_HOSTS = 'base-project.fly.dev,base-project.internal,localhost,127.0.0.1'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
